### ISSUE TITLE
 LogTracker_CharacterData_US - Updates

### ISSUE THREAD

**Issue by Synthez542** [ForsakenNGS/LogTracker#12]
Any ability to auto update this data daily? Or document for those that can pull their own and implement into the addon?

Looks like 
LogTracker_CharacterData_US hasn't been updated in almost 1 month.

**Comment by SamuliPolvi** [comment]
https://www.reddit.com/r/wotlk/comments/10o7fr2/alternative_to_logtracker_addon/

People are asking updates on reddit too. @ForsakenNGS how can we help you to update data?
If you can give/open source the scraper we all can pitch in! And maybe change the update to weekly rather than daily?

**Comment by ForsakenNGS** [comment]
See #13 I could release the code, but it breaks the TOS of warcraftlogs and may result in the account being banned. Until there is an official data source that allows this, I will maintain the freshly released intermediate solution that just shows the raid progression.
