### ISSUE TITLE
Lua errors just being in dalaran

### ISSUE THREAD

**Issue by holypalaswe** [ForsakenNGS/LogTracker#3]
52x LogTracker\LogTracker-1.2.0.lua:199: bad argument #1 to 'gsub' (string expected, got nil)
[string "=[C]"]: in function `gsub'
[string "@LogTracker\LogTracker-1.2.0.lua"]:199: in function <LogTracker\LogTracker.lua:198>
[string "=(tail call)"]: ?
[string "@LogTracker\LogTracker-1.2.0.lua"]:374: in function `GetPlayerZonePerformance'a
[string "@LogTracker\LogTracker-1.2.0.lua"]:407: in function `SendPlayerInfoToChat'
[string "@LogTracker\LogTracker-1.2.0.lua"]:136: in function `OnChatMsgSystem'
[string "@LogTracker\LogTracker-1.2.0.lua"]:101: in function <LogTracker\LogTracker.lua:97>

Locals:
(*temporary) = nil
(*temporary) = "%%w"
(*temporary) = 14
(*temporary) = "string expected, got nil"

**Comment by ForsakenNGS** [comment]
I'm pretty sure I fixed that one independend from your report already, if the issue persists with the current version, please update the error message and I'll have a closer look.
