### ISSUE TITLE
[Bug] "LFG-Integration" does not appear to be working?

### ISSUE THREAD

**Issue by vjtd3** [ForsakenNGS/LogTracker#8]
There's an option for LFG integration that says it's supposed to add LogTracker info to the tooltips in the LFG tool, but it does not appear to be working. This is what I'm seeing when mousing over someone:
![mouseover](https://i.imgur.com/vIR7pmy.png)

I'm not experiencing any lua errors.

Love your addon and can't wait to see it grow in popularity. This'll hopefully set a higher standard for the community as a whole.

**Comment by ForsakenNGS** [comment]
Thanks for your report (and the compliments ;) ). I didn't yet adjust the integration for the wotlk version of the group finder. It should work now with the latest version (1.2.4)
